### ISSUE TITLE
Unable to connect to spark cloud.: code: 404

### ISSUE THREAD

**Issue by a0viedo** [rwaldron/spark-io#47]
While I'm able to use the Web IDE and spark-cli, I can't connect using spark-io (created `.sparkrc` and modified `.bashrc`).
The code:
```js
var Spark = require("spark-io");
var board = new Spark({
  token: process.env.SPARK_TOKEN,
  deviceId: process.env.SPARK_DEVICE_ID
});

board.on("ready", function() {
  console.log("CONNECTED");
  this.pinMode("D7", this.MODES.OUTPUT);

  var byte = 0;

  // This will "blink" the on board led
  setInterval(function() {
    this.digitalWrite("D7", (byte ^= 1));
  }.bind(this), 500);
});


board.on('error', function(err) {
    console.log(err);
});
```
I'm getting this error:
```
Error: Unable to connect to spark cloud.: code: 404
    at IncomingMessage.<anonymous> (/home/a0viedo/Documents/jsPlayground/node_modules/spark-io/lib/spark.js:282:19)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickCallback (node.js:442:13)
```

Any ideas?

**Comment by rwaldron** [comment]
Have you flashed your Spark with the Voodoospark firmware? https://github.com/rwaldron/spark-io#getting-started

**Comment by rwaldron** [comment]
I just double checked:

- spark-io master
- latest voodoospark firmware

Everything works as expected.

**Comment by a0viedo** [comment]
For some reason my core was listed offline with `spark list`. Rebooted the core and then it worked fine. Thanks @rwaldron.
