### ISSUE TITLE
pulseIn

### ISSUE THREAD

**Issue by Brasilikum** [rwaldron/spark-io#59]
Would be nice if support for "pulseIn" could be added.

The example:

```javascript
board.on("ready", function() {
  var ping = new five.Ping('D4');
  ping.on("change", function() {
    console.log("Object is " + this.in + " inches away");
  });
});
```
results in: 

```
TypeError: Object #<Spark> has no method 'pulseIn'
    at Ping.<anonymous> (/home/georgzahlz/johnny/node_modules/johnny-five/lib/ping.js:45:13)
    at wrapper [as _onTimeout] (timers.js:261:14)
    at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)

```

**Comment by Resseguie** [comment]
Ping requires a special firmata be installed, even on plain ol' Arduino. Not sure what it'd require to implement something similar on the Spark. 
See: https://github.com/rwaldron/johnny-five/wiki/Ping

**Comment by rwaldron** [comment]
> Ping requires a special firmata be installed

To elaborate: `pulseIn` is not supported in the Firmata protocol, because it's a process blocking operation. Unfortunately, the version of Firmata we have to support `Ping` isn't a generalized implementation—it's specifically for a `Ping` sensor. 

Incidentally, `pulseIn` doesn't appear to be provided in the Spark's environment: https://github.com/spark/firmware . There are a few forum discussions that offer some sound solutions, but I have serious concerns about adding an operation that requires process blocking on the Spark itself, where it already suffers from wifi latency.

**Comment by Brasilikum** [comment]
Ok, I understand that.
[This solution](https://github.com/timothybrown/Spark-Core-Sundries/blob/master/function_pulseIn.cpp#2) really seems to be blocking:
```
// Wait for the pin to enter target state while keeping track of the timeout.
```
